version: "2"

services:
  crossover:
    build:
      context: ../target/docker/stage
    container_name: crossover
    networks:
      - test-network
      - main-network
    depends_on:
      - crossover_rabbitmq

  crossover_rabbitmq:
    image: rabbitmq
    container_name: crossover.rabbitmq
    networks:
      - test-network
      - main-network


networks:
  test-network:
    driver: bridge
  main-network:
    driver: bridge
