version: "2"

services:
  crossover:
    image: registry.tools.trood.ru/crossover:1.0.1
    container_name: crossover
    volumes:
      - ./conf-example.conf:/opt/configuration/crossover.conf
    depends_on:
      - crossover_rabbitmq

  crossover_rabbitmq:
    image: rabbitmq
    container_name: crossover.rabbitmq

  druid:
    build:
      context: ./druid
    image: druid
    container_name: druid
    ports:
      - "8082:8082"
      - "8090:8090"