version: "2"

services:
  crossover:
    build:
      context: ../target/docker/stage
    container_name: crossover
    networks:
      - trood_test-network
      - trood_main-network
    depends_on:
      - crossover_rabbitmq

  crossover_rabbitmq:
    image: rabbitmq
    container_name: crossover.rabbitmq
    networks:
      - trood_test-network
      - trood_main-network


networks:
  trood_test-network:
    driver: bridge
  trood_main-network:
    driver: bridge
